package test;

import java.awt.Rectangle;
import java.awt.Shape;
import javaswingdev.picturebox.DefaultPictureBoxRender;
import javaswingdev.picturebox.PictureBox;

/**
 *
 * @author raven
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new javaswingdev.picturebox.PictureBox();
        comboBoxFit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboRender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboRenderType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/test/img.jpg"))); // NOI18N

        comboBoxFit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "CONTAIN", "FILL", "COVER", "FIT_WIDTH", "FIT_HEIGHT" }));
        comboBoxFit.setSelectedIndex(3);
        comboBoxFit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFitActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("BoxFit");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Render");

        comboRender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Round", "Circle" }));
        comboRender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRenderActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Render Type");

        comboRenderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAGE", "COMPONENT" }));
        comboRenderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRenderTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboRender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboRenderType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxFit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRenderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboRender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboRenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRenderActionPerformed
        int index = comboRender.getSelectedIndex();
        if (index == 0) {
            pictureBox1.setPictureBoxRender(new DefaultPictureBoxRender());
        } else if (index == 1) {
            pictureBox1.setPictureBoxRender(new DefaultPictureBoxRender() {
                @Override
                public Shape render(Rectangle rectangle) {
                    return createRound(rectangle, 25);
                }
            });
        } else if (index == 2) {
            pictureBox1.setPictureBoxRender(new DefaultPictureBoxRender() {
                @Override
                public Shape render(Rectangle rectangle) {
                    return createCircle(rectangle);
                }
            });
        }
    }//GEN-LAST:event_comboRenderActionPerformed

    private void comboBoxFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFitActionPerformed
        int index = comboBoxFit.getSelectedIndex();
        if (index == 0) {
            pictureBox1.setBoxFit(PictureBox.BoxFit.NONE);
        } else if (index == 1) {
            pictureBox1.setBoxFit(PictureBox.BoxFit.CONTAIN);
        } else if (index == 2) {
            pictureBox1.setBoxFit(PictureBox.BoxFit.FILL);
        } else if (index == 3) {
            pictureBox1.setBoxFit(PictureBox.BoxFit.COVER);
        } else if (index == 4) {
            pictureBox1.setBoxFit(PictureBox.BoxFit.FIT_WIDTH);
        } else if (index == 5) {
            pictureBox1.setBoxFit(PictureBox.BoxFit.FIT_HEIGHT);
        }
    }//GEN-LAST:event_comboBoxFitActionPerformed

    private void comboRenderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRenderTypeActionPerformed
        int index = comboRenderType.getSelectedIndex();
        if (index == 0) {
            pictureBox1.setRenderType(PictureBox.RenderType.IMAGE);
        } else if (index == 1) {
            pictureBox1.setRenderType(PictureBox.RenderType.COMPONENT);
        }
    }//GEN-LAST:event_comboRenderTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxFit;
    private javax.swing.JComboBox<String> comboRender;
    private javax.swing.JComboBox<String> comboRenderType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javaswingdev.picturebox.PictureBox pictureBox1;
    // End of variables declaration//GEN-END:variables
}
